# 1. Imports

In [1]:
import pandas as pd
from pathlib import Path
import os

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.window import Window
from pyspark.sql.types import *

pd.set_option('display.max_columns', None)

# 2. Funções

## 2.1. Função para pegar os eventos de uma temporada nos arquivos parquet

In [2]:
def get_season_events_parquet_file_paths(events_competition_season_folder_path):
    
    season_events_parquet_file_paths = [
        str(Path(events_competition_season_folder_path) / season_event_parquet_file) 
        for season_event_parquet_file in os.listdir(events_competition_season_folder_path) 
        if season_event_parquet_file.endswith('.parquet')
        ]
    
    return season_events_parquet_file_paths

# 3. Preparação dos dados

## 3.1. Criação da Sessão Spark

In [3]:
# Criação da sessão Spark local
spark = SparkSession.builder.master("local[*]").appName("feature_engineering").getOrCreate()

## 3.2. Criação do df para pegar os eventos de todas as partidas da temporada de 2022-2023 da Premier League

(dps pode ser interessante levar a parte do schema dos jogadores e da bola p etapa de extração)

In [4]:
# competition_id = 1 (Premier League)
# season = 2022-2023
events_competition_season_folder_path = str(Path().resolve().parent.parent / "data" / "events" / "1" / "2022-2023")

season_events_parquet_file_paths = get_season_events_parquet_file_paths(events_competition_season_folder_path)

# Criação do dataframe concatenando todos os arquivos parquet dos eventos das partidas entre as temporadas de todas as competições
df_events = spark.read.parquet(*season_events_parquet_file_paths)

df_events = df_events.withColumnsRenamed({
    "id": "eventId",
    "player.id": "eventPlayer.id",
    "player.name": "eventPlayer.name",
    "team.id": "eventTeam.id",
    "team.name": "eventTeam.name",
})

In [5]:
#df_events.select('homePlayers', 'awayPlayers', 'balls').first()

In [6]:
events_competition_season_folder_path = str(Path().resolve().parent.parent / "data" / "events" / "1" / "2022-2023")

season_events_parquet_file_paths = get_season_events_parquet_file_paths(events_competition_season_folder_path)

# Criação do dataframe concatenando todos os arquivos parquet dos eventos das partidas entre as temporadas de todas as competições
df_events = spark.read.parquet(*season_events_parquet_file_paths)

df_events = df_events.withColumnsRenamed({
    "id": "eventId",
    "player.id": "eventPlayer.id",
    "player.name": "eventPlayer.name",
    "team.id": "eventTeam.id",
    "team.name": "eventTeam.name",
})

# Schema em Pyspark para poder parsear o json dos dados de tracking dos jogadores que está como string
players_schema = ArrayType(
    StructType([
        #StructField("speed", FloatType(), True),
        StructField("x", FloatType(), True),
        StructField("y", FloatType(), True),
        StructField("player", StructType([
            StructField("id", IntegerType(), True), 
            StructField("name", StringType(), True)]), 
            True),
        StructField("visibility", StringType(), True),
        StructField("confidence", StringType(), True),
        #StructField("jerseyNum", StringType(), True)      
    ])
)

# Schema em Pyspark para poder parsear o json dos dados de tracking da bola que está como string
balls_schema = ArrayType(
    StructType([
        StructField("x", FloatType(), True),
        StructField("y", FloatType(), True),
        StructField("z", FloatType(), True),
        StructField("visibility", StringType(), True)
    ])
)

details_schema = MapType(StringType(), StringType())

df_events = df_events.withColumns({
    # Cria coluna com json parseado para Lista de dicionários para dados de tracking do time mandante
    "homePlayers_parsed": F.from_json("homePlayers", players_schema),
    
    # Cria coluna com json parseado para Lista de dicionários para dados de tracking do time adversário
    "awayPlayers_parsed": F.from_json("awayPlayers", players_schema),

    # Cria coluna com json parseado para dicionário para dados de tracking da bola
    "balls_parsed": F.from_json("balls", balls_schema),

    "details_parsed": F.from_json("details", details_schema)

}).drop('homePlayers', 'awayPlayers', 'balls', 'details')

df_events = df_events.select(
    'competitionId',
    'season', # dps mudar pra seasonId se necessário
    'gameId',
    'eventId',
    'eventType',
    'eventTypeDescription',
    'period',
    #'periodDescription',
    'startFormattedGameClock',
    'startGameClock',
    #'details_parsed',
    'homeTeam',
    F.col('`eventPlayer.id`').alias('eventPlayerId'),
    F.col('`eventPlayer.name`').alias('eventPlayerName'),
    F.col('`eventTeam.id`').alias('eventTeamId'), 
    F.col('`eventTeam.name`').alias('eventTeamName'), 
    'homePlayers_parsed', 
    'awayPlayers_parsed', 
    'balls_parsed'
)

In [7]:
#df_events.filter(F.size("homePlayers_parsed") == 0).show()

In [8]:
#df_events.filter(F.size("awayPlayers_parsed") == 0).show()

In [9]:
#df_events.filter(F.size("balls_parsed") == 0).show()

In [10]:
print('Quantidade de linhas:', df_events.count())

Quantidade de linhas: 945154

## 3.2. Obter jogos da temporada e ajustar identificação do mandante/adversário

(dps pode ser interessante levar isso p etapa de extração)

In [11]:
games_path = str(Path().resolve().parent.parent / "data" / "games.csv")

df_games = spark.read.csv(games_path, header=True)

df_games_raw = df_games.withColumnRenamed("id","gameId").filter(F.col('season') == '2022-2023')

#df_games_raw.show()

In [12]:
df_games_raw.select('venueType').distinct().show()

+-------------+
|    venueType|
+-------------+
|      NEUTRAL|
|OPPONENT_HOME|
|    TEAM_HOME|
+-------------+

In [13]:
df_games_raw.filter(F.col('venueType') == 'NEUTRAL').select('gameId', 'date', 'season', 'venueType', '`team.name`', '`opponentTeam.name`', '`stadium.name`').sort('date').show(truncate=False)

+------+----------+---------+---------+----------------------+-----------------------+-------------+
|gameId|date      |season   |venueType|team.name             |opponentTeam.name      |stadium.name |
+------+----------+---------+---------+----------------------+-----------------------+-------------+
|4443  |2022-08-06|2022-2023|NEUTRAL  |Chelsea               |Everton                |Goodison Park|
|4458  |2022-08-20|2022-2023|NEUTRAL  |Everton               |Nottingham Forest      |Goodison Park|
|4490  |2022-09-03|2022-2023|NEUTRAL  |Everton               |Liverpool              |Goodison Park|
|4510  |2022-09-18|2022-2023|NEUTRAL  |Everton               |West Ham               |Goodison Park|
|4531  |2022-10-09|2022-2023|NEUTRAL  |Everton               |Manchester United      |Goodison Park|
|4558  |2022-10-22|2022-2023|NEUTRAL  |Crystal Palace        |Everton                |Goodison Park|
|4578  |2022-11-05|2022-2023|NEUTRAL  |Everton               |Leicester City         |Goodison Park|
|4601  |2022-12-26|2022-2023|NEUTRAL  |Everton               |Wolverhampton Wanderers|Goodison Park|
|4621  |2023-01-03|2022-2023|NEUTRAL  |Brighton & Hove Albion|Everton                |Goodison Park|
|4630  |2023-01-14|2022-2023|NEUTRAL  |Everton               |Southampton            |Goodison Park|
|4650  |2023-02-04|2022-2023|NEUTRAL  |Arsenal               |Everton                |Goodison Park|
|4670  |2023-02-18|2022-2023|NEUTRAL  |Everton               |Leeds United           |Goodison Park|
|4678  |2023-02-25|2022-2023|NEUTRAL  |Aston Villa           |Everton                |Goodison Park|
|4697  |2023-03-11|2022-2023|NEUTRAL  |Brentford             |Everton                |Goodison Park|
|4720  |2023-04-03|2022-2023|NEUTRAL  |Everton               |Tottenham Hotspur      |Goodison Park|
|4737  |2023-04-15|2022-2023|NEUTRAL  |Everton               |Fulham                 |Goodison Park|
|4755  |2023-04-27|2022-2023|NEUTRAL  |Everton               |Newcastle United       |Goodison Park|
|4790  |2023-05-14|2022-2023|NEUTRAL  |Everton               |Manchester City        |Goodison Park|
|4810  |2023-05-28|2022-2023|NEUTRAL  |AFC Bournemouth       |Everton                |Goodison Park|
+------+----------+---------+---------+----------------------+-----------------------+-------------+

- Apesar de Goodison Park teoricamente ser estádio do Everton e se tratarem de todos os jogos do Everton, o venueType é neutro. Por conta disso, não irei considerar essas partidas.
- Caso necessário usá-las futuramente, podemos ver como ficam os eventos de home e away e se seguem essa estrutura acima mesmo o estádio sendo neutro. Uma sugestão pode ser considerar sempre Everton como casa, mas teria que ver se os eventos de posse ficam de acordo.

In [14]:
df_games_raw = df_games_raw.filter(F.col('venueType').isin(['TEAM_HOME', 'OPPONENT_HOME']))

In [15]:
# se venueType == TEAM_HOME, (homeTeam.id == team.id e homeTeam.name == team.name) e (opponentTeam.id == opponentTeam.id e opponentTeam.name == opponentTeam.name)
# se venueType == OPPONENT_HOME, (homeTeam.id == opponentTeam.id e homeTeam.name == opponentTeam.name) e (opponentTeam.id == team.id e opponentTeam.name == team.name)
df_games = (
    df_games_raw
    .withColumns({
        "homeTeamId": F.when(F.col("venueType") == "TEAM_HOME", F.col("`team.id`")).otherwise(F.col("`opponentTeam.id`")),
        "homeTeamName": F.when(F.col("venueType") == "TEAM_HOME", F.col("`team.name`")).otherwise(F.col("`opponentTeam.name`")),
        
        "opponentTeamId": F.when(F.col("venueType") == "TEAM_HOME", F.col("`opponentTeam.id`")).otherwise(F.col("`team.id`")),
        "opponentTeamName": F.when(F.col("venueType") == "TEAM_HOME", F.col("`opponentTeam.name`")).otherwise(F.col("`team.name`")),
    })
    .select(
        'gameId', 
        'date',
        'season',
        F.col('`competition.id`').alias('competitionId'),
        F.col('`competition.name`').alias('competitionName'),
        'venueType',
        'homeTeamId',
        'homeTeamName',
        'opponentTeamId',
        'opponentTeamName',
        F.col('teamStartSide').alias('homeTeamStartSide'),
        F.col('`stadium.name`').alias('stadiumName'), 
        F.col('`stadium.length`').cast("float").alias('stadiumLength'), 
        F.col('`stadium.width`').cast("float").alias('stadiumWidth')
    )
)

# df_games.show(5)

## 4. Junção dos dados dos Jogos + Eventos em uma tabela

In [16]:
# left join dos eventos + informações dos jogos
df_games_events = (
    df_events
    .join(
        df_games.drop('season', 'competitionId', 'competitionName'), 
        on = "gameId", 
        how='left'
    )
    # filtro para remover os jogos que tinha mandante neutro (venueType == NEUTRAL)
    .filter(~F.col('date').isNull())
)

df_games_events = (
    df_games_events
    .withColumn(
        'homeTeamAttackDirection',
            F.when(
                ((F.col('period') == 1) & (F.col('homeTeamStartSide') == 'Right')) | 
                ((F.col('period') == 2) & (F.col('homeTeamStartSide') == 'Left')), 
                'Left'
            )
            .when(
                ((F.col('period') == 1) & (F.col('homeTeamStartSide') == 'Left')) | 
                ((F.col('period') == 2) & (F.col('homeTeamStartSide') == 'Right')), 
                'Right'
            )
        )
    .withColumn(
            'awayTeamAttackDirection',
            F.when(F.col('homeTeamAttackDirection') == 'Right', 'Left')
            .when(F.col('homeTeamAttackDirection') == 'Left', 'Right')
        )
    .drop('homeTeamStartSide')
)

df_games_events.show(5)

+------+-------------+---------+--------------------+------------+--------------------+------+-----------------------+--------------+--------+-------------+---------------+-----------+-------------+--------------------+--------------------+--------------------+----------+---------+----------+---------------+--------------+----------------+----------------+-------------+------------+-----------------------+-----------------------+
|gameId|competitionId|   season|             eventId|   eventType|eventTypeDescription|period|startFormattedGameClock|startGameClock|homeTeam|eventPlayerId|eventPlayerName|eventTeamId|eventTeamName|  homePlayers_parsed|  awayPlayers_parsed|        balls_parsed|      date|venueType|homeTeamId|   homeTeamName|opponentTeamId|opponentTeamName|     stadiumName|stadiumLength|stadiumWidth|homeTeamAttackDirection|awayTeamAttackDirection|
+------+-------------+---------+--------------------+------------+--------------------+------+-----------------------+--------------+--------+-------------+---------------+-----------+-------------+--------------------+--------------------+--------------------+----------+---------+----------+---------------+--------------+----------------+----------------+-------------+------------+-----------------------+-----------------------+
|  4438|            1|2022-2023|9e6a498f54bad910e...|          PA|                Pass|     1|                  00:00|             0|   false|          402|     Danny Ings|          3|  Aston Villa|[{15.746, 25.001,...|[{-17.929, 4.63, ...|[{-4.7, -0.13, 0....|2022-08-06|TEAM_HOME|         1|AFC Bournemouth|             3|     Aston Villa|Vitality Stadium|        105.0|        68.0|                   Left|                  Right|
|  4438|            1|2022-2023|60717c0b4d7bb1d57...|FIRSTKICKOFF| First half kick off|     1|                  00:00|             0|   false|          402|     Danny Ings|          3|  Aston Villa|[{15.746, 25.001,...|[{-17.929, 4.63, ...|[{-4.7, -0.13, 0....|2022-08-06|TEAM_HOME|         1|AFC Bournemouth|             3|     Aston Villa|Vitality Stadium|        105.0|        68.0|                   Left|                  Right|
|  4438|            1|2022-2023|8768655f3e751580b...|          PA|                Pass|     1|                  00:01|             1|   false|         1788|   Diego Carlos|          3|  Aston Villa|[{11.349, 21.9, {...|[{-20.167, 2.954,...|[{-20.53, 2.06, 0...|2022-08-06|TEAM_HOME|         1|AFC Bournemouth|             3|     Aston Villa|Vitality Stadium|        105.0|        68.0|                   Left|                  Right|
|  4438|            1|2022-2023|05cfea7838512ae4e...|         OTB|A possession with...|     1|                  00:01|             1|   false|         1788|   Diego Carlos|          3|  Aston Villa|[{11.349, 21.9, {...|[{-20.167, 2.954,...|[{-20.53, 2.06, 0...|2022-08-06|TEAM_HOME|         1|AFC Bournemouth|             3|     Aston Villa|Vitality Stadium|        105.0|        68.0|                   Left|                  Right|
|  4438|            1|2022-2023|a084905de5dc02ce4...|          PA|                Pass|     1|                  00:04|             4|   false|         1896|   Matthew Cash|          3|  Aston Villa|[{3.131, 5.468, {...|[{-24.306, 5.275,...|[{-6.76, -27.81, ...|2022-08-06|TEAM_HOME|         1|AFC Bournemouth|             3|     Aston Villa|Vitality Stadium|        105.0|        68.0|                   Left|                  Right|
+------+-------------+---------+--------------------+------------+--------------------+------+-----------------------+--------------+--------+-------------+---------------+-----------+-------------+--------------------+--------------------+--------------------+----------+---------+----------+---------------+--------------+----------------+----------------+-------------+------------+-----------------------+-----------------------+
only showing top 5 rows

In [17]:
df_games_events.groupby('period').count().show()

+------+------+
|period| count|
+------+------+
|     1|456103|
|     2|442797|
+------+------+

In [18]:
# variável que indica o time com a posse
df_games_events.groupBy('homeTeam').count().show()

+--------+------+
|homeTeam| count|
+--------+------+
|    NULL|  6538|
|    true|451847|
|   false|440515|
+--------+------+

In [19]:
# window function pra criação do Id de posse
w_pos = (
    Window
    .partitionBy(
        "competitionId",
        "season",
        "gameId"
    )
    .orderBy("startGameClock")
)

df_games_events = (
    df_games_events
    .filter(
        # filtro para garantir apenas eventos das partidas no 1º e 2º tempo
        (F.col('period').isin([1,2])) &
        # filtro para não considerar tracking da bola e jogadores home/away que n tem tracking (dps podemos pensar em imputar)
        (F.size("balls_parsed") != 0) & (F.size("homePlayers_parsed") != 0) & (F.size("awayPlayers_parsed") != 0)
    ) 
    .dropna(subset='homeTeam') # drop nos eventos onde nenhum dos dois times tem a posse
    .withColumn(
        "possession_id",
        F.sum(
            F.when(
                F.col("homeTeam") != F.lag("homeTeam").over(w_pos), 1
            ).otherwise(0)
        ).over(
            w_pos.rowsBetween(Window.unboundedPreceding, Window.currentRow)
        )
    )
)

## Normalização do ataque sempre pra direita

In [20]:
# time com a posse está atacando e time sem está defendendo

df_games_events_tracking = (
    df_games_events
    # time atacando = se o time da casa tiver a posse, pega tracking home, se não pega tracking away
    .withColumn(
        "attackingPlayers",
        F.when(F.col("homeTeam"), F.col("homePlayers_parsed"))
        .otherwise(F.col("awayPlayers_parsed"))
    )
    # time defendendo = se o time da casa tiver a posse, pega tracking away, se não pega tracking home
    .withColumn(
        "defendingPlayers",
        F.when(F.col("homeTeam"), F.col("awayPlayers_parsed"))
        .otherwise(F.col("homePlayers_parsed"))
    )
    .withColumn(
        "attackingDirection",
        F.when(F.col("homeTeam"), F.col("homeTeamAttackDirection"))
        .otherwise(F.col("awayTeamAttackDirection"))
    )
    # flag para normalização (para tratar ataque sempre pra direita)
    .withColumn(
        "need_side_revert",
        F.col("attackingDirection") == "Left"
    )
    .drop(
        'homePlayers_parsed',  
        'awayPlayers_parsed',
        'homeTeamAttackDirection',
        'awayTeamAttackDirection'
    )
)

#df_games_events_tracking.show()

In [21]:
players_tracking_norm = (
        lambda p: F.struct(
            # reversão do eixo horizontal qnd necessário
            F.when(F.col("need_side_revert"), -p["x"])
            .otherwise(p["x"])
            .alias("x"),
            # variáveis restantes mantém igual
            p["y"].alias("y"),            
            p["player"].alias("player"),
            p["visibility"].alias("visibility"),
            p["confidence"].alias("confidence")
        )
)

balls_norm = (
    F.transform(
        "balls_parsed",
        lambda b: F.struct(
            # reversão do eixo horizontal qnd necessário
            F.when(F.col("need_side_revert"), -b["x"])
            .otherwise(b["x"])
            .alias("x"),
            # variáveis restantes mantém igual            
            b["y"].alias("y"),
            b["z"].alias("z"),            
            b["visibility"].alias("visibility")
        )
    )
)

# df para normalizar os atacantes, defensores e bola sempre atacando do lado direito
df_games_events_tracking_norm = (
    df_games_events_tracking
    # normalizar atacantes
    .withColumns({
        "attackingPlayersNorm": F.transform("attackingPlayers", players_tracking_norm),
        # normalizar defensores
        "defendingPlayersNorm": F.transform("defendingPlayers", players_tracking_norm),
        # normalizar a bola
        "ballsNorm": balls_norm
    }).drop(
        'attackingPlayers', 
        'defendingPlayers',
        'balls_parsed',
        'attackingDirection',
        'need_side_revert'
        )
)

In [22]:
def euclidean_dist(x1, y1, x2, y2):
    return F.sqrt(
        F.pow(x1 - x2, 2) +
        F.pow(y1 - y2, 2)
    )

In [23]:
# Extremos esquerdo e direito do campo no plano cartesiano
left_x = -F.col('stadiumLength') / 2
right_x = F.col('stadiumLength') / 2

# Extremos superior e inferior do campo no plano cartesiano
top_y = F.col('stadiumWidth') / 2
bottom_y = -F.col('stadiumWidth') / 2

# Eixos x e y da posição da bola a partir dos dados de tracking
ball_x = F.get("ballsNorm", 0)["x"]
ball_y = F.get("ballsNorm", 0)["y"]

# Menor distância euclidiana entre os escanteios do lado esquerdo até a bola
progression_distance = F.round(
    F.least(
        euclidean_dist(ball_x, ball_y, left_x, top_y),
        euclidean_dist(ball_x, ball_y, left_x, bottom_y)
    ), 2)

## Criação das componentes de ameaça

- Métrica 1: Distância percorrida no campo (medida pela menor distância entre os escanteios do time com a posse até a bola) 
    - Hipótese: Quanto mais o jogador com posse percorrer o campo com a bola na direção do gol, maior a ameaça de gol por estar mais próximo dele.
    - Relação: Diretamente proporcional
- Métrica 2: Quantidade total de jogadores dos dois times (entre a bola e o gol)
    - Hipótese: Quanto MAIS jogadores dos dois times entre a bola e gol, MENOR a ameaça de gol por haver maior possibilidade de alguma ação defensiva e também por haver chances de um possível chute ser bloqueado.
    - Relação: Inversamente proporcional
- Métrica 3: Vantagem numérica do ataque em relação à defesa (entre a bola e o gol)
    - Hipótese: Quanto MAIOR a vantagem numérica do ataque em relação à defesa, MAIOR a ameaça de gol por ter maiores chance de ações ofensivas e menores chances de ações defensivas
    - Relação: Diretamente proporcional

In [24]:
df_games_events_players_ball_goal = (
    df_games_events_tracking_norm
     .withColumns({
        # Quantidade de jogadores do time mandante entre o gol esquerdo e a bola
        'attackers_between_ball_goal': (
            F.size(
                F.filter(
                    F.col('attackingPlayersNorm'),
                    lambda p: (
                        # jogadores no eixo x entre a bola e o gol direito
                        (p['x'] <= right_x) &
                        (p['x'] >= ball_x)
                    )
                )
            )
        ),
        'defenders_between_ball_goal': (
            F.size(
                F.filter(
                    F.col('defendingPlayersNorm'),
                    lambda p: (
                        # jogadores no eixo x entre a bola e o gol direito
                        (p['x'] <= right_x) &
                        (p['x'] >= ball_x)
                    )
                )
            )
        )
    })
)

df_games_events_players_ball_goal = (
    df_games_events_players_ball_goal.withColumns({
        # Progressão em campo em direção ao gol defendido
        'progression_distance': progression_distance,
        
        # Quantidade absoluta de jogadores entre a bola e o gol
        'total_players_between_ball_goal': F.col('attackers_between_ball_goal') + F.col('defenders_between_ball_goal'),
        
        # Vantagem numérica do ataque em relação à defesa
        'atk_def_advantage_between_ball_goal': F.col('attackers_between_ball_goal') - F.col('defenders_between_ball_goal')
    })
)

# df_games_events_players_ball_goal.show()

### Criação da Ameaça pela Média das 3 componentes normalizadas com Min-Max

In [25]:
# Obtém mínimos e máximos das componentes
stats = (
    df_games_events_players_ball_goal
    .agg(
        F.min("progression_distance").alias("min_pd"),
        F.max("progression_distance").alias("max_pd"),

        F.min("total_players_between_ball_goal").alias("min_tp"),
        F.max("total_players_between_ball_goal").alias("max_tp"),

        F.min("atk_def_advantage_between_ball_goal").alias("min_adv"),
        F.max("atk_def_advantage_between_ball_goal").alias("max_adv")
    )
    .first()
)

df_games_events_players_ball_goal_norm = (
    df_games_events_players_ball_goal
    # Componentes normalizadas [0,1]
    .withColumns({
        # Progressão em campo em direção ao gol defendido
        "progression_distance_norm":
        F.round((F.col("progression_distance") - F.lit(stats["min_pd"])) / F.lit(stats["max_pd"] - stats["min_pd"]), 3),

        # Quantidade absoluta de jogadores entre a bola e o gol (1 - minmax por ser inversamente proporcional)
        "total_players_between_ball_goal_norm": F.round(1 - 
        (F.col("total_players_between_ball_goal") - F.lit(stats["min_tp"])) / F.lit(stats["max_tp"] - stats["min_tp"]), 3), 
        
        # Vantagem numérica do ataque em relação à defesa
        "atk_def_advantage_between_ball_goal_norm":
        F.round((F.col("atk_def_advantage_between_ball_goal") - F.lit(stats["min_adv"])) / F.lit(stats["max_adv"] - stats["min_adv"]), 3),

        # Threat score = média das 3 componentes
        "threat_score": F.round((
            F.col("progression_distance_norm") + F.col("total_players_between_ball_goal_norm") + F.col("atk_def_advantage_between_ball_goal_norm")
        ) / F.lit(3.0), 3)

    })
)

In [ ]:
# window function por competição-temporada-jogo-time com posse
w = (
    Window
    .partitionBy(
        "competitionId",
        "season",
        "gameId",
        "homeTeam"
    )
    .orderBy("startGameClock")
)

df_threat_final = (
    df_games_events_players_ball_goal_norm
    .withColumn(
        "threat_score_delta",
        F.round(F.coalesce(F.col("threat_score") - F.lag("threat_score").over(w), F.lit(0.0)), 3))
)

#df_threat_final.show()

+------+-------------+---------+--------------------+---------+--------------------+------+-----------------------+--------------+--------+-------------+------------------+-----------+-------------+----------+-------------+----------+--------------+--------------+----------------+-------------+-------------+------------+-------------+--------------------+--------------------+--------------------+---------------------------+---------------------------+--------------------+-------------------------------+-----------------------------------+-------------------------+------------------------------------+----------------------------------------+------------+------------------+
|gameId|competitionId|   season|             eventId|eventType|eventTypeDescription|period|startFormattedGameClock|startGameClock|homeTeam|eventPlayerId|   eventPlayerName|eventTeamId|eventTeamName|      date|    venueType|homeTeamId|  homeTeamName|opponentTeamId|opponentTeamName|  stadiumName|stadiumLength|stadiumWidth|possession_id|attackingPlayersNorm|defendingPlayersNorm|           ballsNorm|attackers_between_ball_goal|defenders_between_ball_goal|progression_distance|total_players_between_ball_goal|atk_def_advantage_between_ball_goal|progression_distance_norm|total_players_between_ball_goal_norm|atk_def_advantage_between_ball_goal_norm|threat_score|threat_score_delta|
+------+-------------+---------+--------------------+---------+--------------------+------+-----------------------+--------------+--------+-------------+------------------+-----------+-------------+----------+-------------+----------+--------------+--------------+----------------+-------------+-------------+------------+-------------+--------------------+--------------------+--------------------+---------------------------+---------------------------+--------------------+-------------------------------+-----------------------------------+-------------------------+------------------------------------+----------------------------------------+------------+------------------+
|  4436|            1|2022-2023|3f6e1aba933c39881...|      OTB|A possession with...|     1|                  00:42|            42|   false|         1916|         Ben White|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            1|[{15.034, 16.403,...|[{-26.424, 8.906,...|[{39.57, 33.03, 2...|                          3|                          1|               90.08|                              4|                                  2|                    0.764|                               0.818|                                   0.591|       0.724|               0.0|
|  4436|            1|2022-2023|6c4649d31d21fe2b0...|       PA|                Pass|     1|                  00:42|            42|   false|         1916|         Ben White|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            1|[{15.034, 16.403,...|[{-26.424, 8.906,...|[{39.57, 33.03, 2...|                          3|                          1|               90.08|                              4|                                  2|                    0.764|                               0.818|                                   0.591|       0.724|               0.0|
|  4436|            1|2022-2023|b27b2e21c90124e60...|       PA|                Pass|     1|                  00:48|            48|   false|         1380|     Thomas Partey|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            3|[{11.183, 19.382,...|[{-27.355, 7.149,...|[{22.79, 31.45, 0...|                          8|                          4|               73.33|                             12|                                  4|                    0.622|                               0.455|                                   0.682|       0.586|            -0.138|
|  4436|            1|2022-2023|4c9957c50be0832d8...|      OTB|A possession with...|     1|                  00:48|            48|   false|         1380|     Thomas Partey|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            3|[{11.183, 19.382,...|[{-27.355, 7.149,...|[{22.79, 31.45, 0...|                          8|                          4|               73.33|                             12|                                  4|                    0.622|                               0.455|                                   0.682|       0.586|               0.0|
|  4436|            1|2022-2023|41beee2afdf6d96bb...|      OTB|A possession with...|     1|                  00:49|            49|   false|         1916|         Ben White|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            3|[{11.142, 19.192,...|[{-27.486, 7.016,...|[{21.9, 27.63, 0....|                          8|                          6|               72.68|                             14|                                  2|                    0.616|                               0.364|                                   0.591|       0.524|            -0.062|
|  4436|            1|2022-2023|12d3afeaf19ce30a6...|       PA|                Pass|     1|                  00:49|            49|   false|         1916|         Ben White|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            3|[{11.142, 19.192,...|[{-27.486, 7.016,...|[{21.9, 27.63, 0....|                          8|                          6|               72.68|                             14|                                  2|                    0.616|                               0.364|                                   0.591|       0.524|               0.0|
|  4436|            1|2022-2023|f252fa04f0f1c9dd9...|       PA|                Pass|     1|                  00:50|            50|   false|         1688|   Martin Ödegaard|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            3|[{12.576, 17.834,...|[{-27.817, 7.4, {...|[{17.52, 27.29, 0...|                          9|                          6|               68.35|                             15|                                  3|                    0.579|                               0.318|                                   0.636|       0.511|            -0.013|
|  4436|            1|2022-2023|bf393301d96e323ba...|      OTB|A possession with...|     1|                  00:50|            50|   false|         1688|   Martin Ödegaard|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            3|[{12.576, 17.834,...|[{-27.817, 7.4, {...|[{17.52, 27.29, 0...|                          9|                          6|               68.35|                             15|                                  3|                    0.579|                               0.318|                                   0.636|       0.511|               0.0|
|  4436|            1|2022-2023|81c3c9ae4a22c8404...|      OTB|A possession with...|     1|                  00:53|            53|   false|          162|Gabriel Martinelli|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            5|[{11.605, 20.306,...|[{-29.554, 6.285,...|[{10.65, 23.12, 1...|                         10|                          7|               62.11|                             17|                                  3|                    0.526|                               0.227|                                   0.636|       0.463|            -0.048|
|  4436|            1|2022-2023|ca5c7a5e9962cbcd8...|       RE|             Rebound|     1|                  00:53|            53|   false|          162|Gabriel Martinelli|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            5|[{11.605, 20.306,...|[{-29.554, 6.285,...|[{10.65, 23.12, 1...|                         10|                          7|               62.11|                             17|                                  3|                    0.526|                               0.227|                                   0.636|       0.463|               0.0|
|  4436|            1|2022-2023|cd74e462bfa72e28d...|       RE|             Rebound|     1|                  01:13|            73|   false|          163|       Bukayo Saka|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            7|[{-4.945, -3.737,...|[{-34.326, 2.435,...|[{21.5, 33.74, -0...|                          4|                          2|                72.0|                              6|                                  2|                     0.61|                               0.727|                                   0.591|       0.643|              0.18|
|  4436|            1|2022-2023|0dff109f263542d5b...|      OTB|A possession with...|     1|                  01:13|            73|   false|          163|       Bukayo Saka|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            7|[{-4.945, -3.737,...|[{-34.326, 2.435,...|[{21.5, 33.74, -0...|                          4|                          2|                72.0|                              6|                                  2|                     0.61|                               0.727|                                   0.591|       0.643|               0.0|
|  4436|            1|2022-2023|3193ae30fa1a96a81...|       CH|           Challenge|     1|                  01:21|            81|   false|         1688|   Martin Ödegaard|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            9|[{9.916, 5.702, {...|[{-31.204, 5.21, ...|[{16.06, 26.4, 0....|                          8|                          4|               66.99|                             12|                                  4|                    0.568|                               0.455|                                   0.682|       0.568|            -0.075|
|  4436|            1|2022-2023|c8d2858e9c73afba4...|      OTB|A possession with...|     1|                  01:21|            81|   false|         1688|   Martin Ödegaard|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            9|[{9.916, 5.702, {...|[{-31.204, 5.21, ...|[{16.06, 26.4, 0....|                          8|                          4|               66.99|                             12|                                  4|                    0.568|                               0.455|                                   0.682|       0.568|               0.0|
|  4436|            1|2022-2023|847b8f8e7146d4079...|       TC|         Touch Carry|     1|                  01:21|            81|   false|         1688|   Martin Ödegaard|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            9|[{9.427, 5.872, {...|[{-31.381, 5.188,...|[{16.0, 28.9, 0.0...|                          8|                          3|                66.7|                             11|                                  5|                    0.565|                                 0.5|                                   0.727|       0.597|             0.029|
|  4436|            1|2022-2023|8a9b0f1881c589dd8...|       PA|                Pass|     1|                  01:21|            81|   false|          163|       Bukayo Saka|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            9|[{8.983, 5.986, {...|[{-31.563, 5.172,...|[{14.95, 29.79, 0...|                          9|                          4|               65.59|                             13|                                  5|                    0.556|                               0.409|                                   0.727|       0.564|            -0.033|
|  4436|            1|2022-2023|dc1b1da0c7b3b944b...|      OTB|A possession with...|     1|                  01:21|            81|   false|          163|       Bukayo Saka|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            9|[{8.983, 5.986, {...|[{-31.563, 5.172,...|[{14.95, 29.79, 0...|                          9|                          4|               65.59|                             13|                                  5|                    0.556|                               0.409|                                   0.727|       0.564|               0.0|
|  4436|            1|2022-2023|9f7b9624c76035b36...|       BC|          Ball Carry|     1|                  01:22|            82|   false|           30|     Gabriel Jesus|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            9|[{-1.427, 4.822, ...|[{-35.055, 5.075,...|[{1.54, 27.54, 0....|                         10|                          5|               52.44|                             15|                                  5|                    0.444|                               0.318|                                   0.727|       0.496|            -0.068|
|  4436|            1|2022-2023|71f7f7116ad0a4fa7...|      OTB|A possession with...|     1|                  01:22|            82|   false|           30|     Gabriel Jesus|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            9|[{-1.427, 4.822, ...|[{-35.055, 5.075,...|[{1.54, 27.54, 0....|                         10|                          5|               52.44|                             15|                                  5|                    0.444|                               0.318|                                   0.727|       0.496|               0.0|
|  4436|            1|2022-2023|61db9da52479750d0...|       TC|         Touch Carry|     1|                  01:22|            82|   false|           30|     Gabriel Jesus|          2|      Arsenal|2022-08-05|OPPONENT_HOME|         7|Crystal Palace|             2|         Arsenal|Selhurst Park|        101.0|        68.0|            9|[{-6.038, 3.029, ...|[{-36.384, 4.86, ...|[{0.79, 24.18, 0....|                          8|                          4|               52.22|                             12|                                  4|                    0.442|                               0.455|                                   0.682|       0.526|              0.03|
+------+-------------+---------+--------------------+---------+--------------------+------+-----------------------+--------------+--------+-------------+------------------+-----------+-------------+----------+-------------+----------+--------------+--------------+----------------+-------------+-------------+------------+-------------+--------------------+--------------------+--------------------+---------------------------+---------------------------+--------------------+-------------------------------+-----------------------------------+-------------------------+------------------------------------+----------------------------------------+------------+------------------+
only showing top 20 rows

### Validação do threat_score criado

In [27]:
filtered_columns = [
    'gameId',
    'competitionId',
    'season',
    'date',
    'eventId',
    'eventType',
    'period',
    'startFormattedGameClock',
    'startGameClock',
    'homeTeam',
    'homeTeamName',
    'opponentTeamName',
    'possession_id',
    'threat_score'
]

df_threat_filtrado = (
    df_threat_final.select(filtered_columns)
)

df_threat_filtrado.show()

+------+-------------+---------+----------+--------------------+------------+------+-----------------------+--------------+--------+--------------+----------------+-------------+------------+
|gameId|competitionId|   season|      date|             eventId|   eventType|period|startFormattedGameClock|startGameClock|homeTeam|  homeTeamName|opponentTeamName|possession_id|threat_score|
+------+-------------+---------+----------+--------------------+------------+------+-----------------------+--------------+--------+--------------+----------------+-------------+------------+
|  4436|            1|2022-2023|2022-08-05|6963e29748b45b531...|FIRSTKICKOFF|     1|                  00:00|             0|    true|Crystal Palace|         Arsenal|            0|       0.646|
|  4436|            1|2022-2023|2022-08-05|6cbfa1cd4e950a89f...|          PA|     1|                  00:00|             0|    true|Crystal Palace|         Arsenal|            0|       0.646|
|  4436|            1|2022-2023|2022-08-05|69e313ee52a0e8454...|          PA|     1|                  00:01|             1|    true|Crystal Palace|         Arsenal|            0|       0.712|
|  4436|            1|2022-2023|2022-08-05|9677e4fce2f14f419...|         OTB|     1|                  00:01|             1|    true|Crystal Palace|         Arsenal|            0|       0.712|
|  4436|            1|2022-2023|2022-08-05|b8aac24ec2e6e4855...|          PA|     1|                  00:03|             3|    true|Crystal Palace|         Arsenal|            0|       0.687|
|  4436|            1|2022-2023|2022-08-05|a8ec3536c77759008...|         OTB|     1|                  00:03|             3|    true|Crystal Palace|         Arsenal|            0|       0.687|
|  4436|            1|2022-2023|2022-08-05|dfd734f274ea0952e...|         OTB|     1|                  00:05|             5|    true|Crystal Palace|         Arsenal|            0|       0.645|
|  4436|            1|2022-2023|2022-08-05|cfa6c66381665427f...|          PA|     1|                  00:05|             5|    true|Crystal Palace|         Arsenal|            0|       0.645|
|  4436|            1|2022-2023|2022-08-05|fc580ef88b51a823e...|         OTB|     1|                  00:07|             7|    true|Crystal Palace|         Arsenal|            0|       0.716|
|  4436|            1|2022-2023|2022-08-05|8c07e0e712eac4ac1...|          PA|     1|                  00:07|             7|    true|Crystal Palace|         Arsenal|            0|       0.716|
|  4436|            1|2022-2023|2022-08-05|9a17eb7534e098594...|          PA|     1|                  00:08|             8|    true|Crystal Palace|         Arsenal|            0|       0.663|
|  4436|            1|2022-2023|2022-08-05|dcb024d1314e89fd6...|         OTB|     1|                  00:08|             8|    true|Crystal Palace|         Arsenal|            0|       0.663|
|  4436|            1|2022-2023|2022-08-05|3f6e1aba933c39881...|         OTB|     1|                  00:42|            42|   false|Crystal Palace|         Arsenal|            1|       0.724|
|  4436|            1|2022-2023|2022-08-05|6c4649d31d21fe2b0...|          PA|     1|                  00:42|            42|   false|Crystal Palace|         Arsenal|            1|       0.724|
|  4436|            1|2022-2023|2022-08-05|d1d90634dee1eb108...|          CH|     1|                  00:44|            44|    true|Crystal Palace|         Arsenal|            2|       0.524|
|  4436|            1|2022-2023|2022-08-05|75f1c20816fb5e394...|         OTB|     1|                  00:44|            44|    true|Crystal Palace|         Arsenal|            2|       0.524|
|  4436|            1|2022-2023|2022-08-05|432ce6adb8330a937...|          PA|     1|                  00:44|            44|    true|Crystal Palace|         Arsenal|            2|       0.524|
|  4436|            1|2022-2023|2022-08-05|524549c5ec7bb9820...|          CH|     1|                  00:45|            45|    true|Crystal Palace|         Arsenal|            2|       0.483|
|  4436|            1|2022-2023|2022-08-05|017a4dcb809d957e7...|         OTB|     1|                  00:45|            45|    true|Crystal Palace|         Arsenal|            2|       0.483|
|  4436|            1|2022-2023|2022-08-05|b27b2e21c90124e60...|          PA|     1|                  00:48|            48|   false|Crystal Palace|         Arsenal|            3|       0.586|
+------+-------------+---------+----------+--------------------+------------+------+-----------------------+--------------+--------+--------------+----------------+-------------+------------+
only showing top 20 rows

In [ ]:
'''df_avg_threat = (
    df_threat_filtrado
    .groupBy(
        "gameId",
        "competitionId",
        "season",
        "date",
        'homeTeamName', 
        'opponentTeamName'
    )
    .agg(
        # ameaça média sofrida do time mandante
        F.round(F.mean(F.when(F.col("homeTeam"), F.col("threat_score"))), 3).alias("avg_threat_score_H"),

        # ameaça média sofrida do time visitante
        F.round(F.mean(F.when(~F.col("homeTeam"), F.col("threat_score"))), 3).alias("avg_threat_score_A")
    )
)

df_avg_threat.show()'''

+------+-------------+---------+----------+--------------------+--------------------+------------------+------------------+
|gameId|competitionId|   season|      date|        homeTeamName|    opponentTeamName|avg_threat_score_H|avg_threat_score_A|
+------+-------------+---------+----------+--------------------+--------------------+------------------+------------------+
|  4450|            1|2022-2023|2022-08-14|             Chelsea|   Tottenham Hotspur|             0.433|             0.377|
|  4436|            1|2022-2023|2022-08-05|      Crystal Palace|             Arsenal|             0.597|             0.579|
|  4441|            1|2022-2023|2022-08-06|    Newcastle United|   Nottingham Forest|             0.454|             0.368|
|  4460|            1|2022-2023|2022-08-21|        Leeds United|             Chelsea|             0.567|             0.572|
|  4465|            1|2022-2023|2022-08-21|            West Ham|Brighton & Hove A...|             0.582|             0.571|
|  4447|            1|2022-2023|2022-08-13|         Aston Villa|             Everton|             0.415|             0.399|
|  4469|            1|2022-2023|2022-08-27|Brighton & Hove A...|        Leeds United|              0.43|             0.391|
|  4461|            1|2022-2023|2022-08-20|      Leicester City|         Southampton|             0.396|             0.423|
|  4449|            1|2022-2023|2022-08-13|Brighton & Hove A...|    Newcastle United|             0.447|             0.411|
|  4438|            1|2022-2023|2022-08-06|     AFC Bournemouth|         Aston Villa|             0.403|             0.402|
|  4451|            1|2022-2023|2022-08-15|           Liverpool|      Crystal Palace|             0.578|             0.576|
|  4442|            1|2022-2023|2022-08-06|   Tottenham Hotspur|         Southampton|             0.584|             0.576|
|  4457|            1|2022-2023|2022-08-20|      Crystal Palace|         Aston Villa|             0.566|             0.592|
|  4444|            1|2022-2023|2022-08-07|   Manchester United|Brighton & Hove A...|             0.583|             0.534|
|  4453|            1|2022-2023|2022-08-14|   Nottingham Forest|            West Ham|             0.427|             0.433|
|  4452|            1|2022-2023|2022-08-13|     Manchester City|     AFC Bournemouth|              0.57|             0.639|
|  4456|            1|2022-2023|2022-08-20|     AFC Bournemouth|             Arsenal|             0.393|             0.404|
|  4464|            1|2022-2023|2022-08-20|   Tottenham Hotspur|Wolverhampton Wan...|             0.418|             0.392|
|  4454|            1|2022-2023|2022-08-13|         Southampton|        Leeds United|             0.563|             0.579|
|  4462|            1|2022-2023|2022-08-22|   Manchester United|           Liverpool|              0.58|             0.577|
+------+-------------+---------+----------+--------------------+--------------------+------------------+------------------+
only showing top 20 rows

In [66]:
df_avg_threat = (
    df_threat_filtrado
    .groupBy(
        "gameId",
        "competitionId",
        "season",
        "date",
        'homeTeamName', 
        'opponentTeamName',
        "homeTeam",
    )
    .agg(
        F.round(F.mean(F.col("threat_score")), 3).alias("avg_threat_score"),
    )
)

df_avg_threat.show()

+------+-------------+---------+----------+--------------------+--------------------+--------+----------------+
|gameId|competitionId|   season|      date|        homeTeamName|    opponentTeamName|homeTeam|avg_threat_score|
+------+-------------+---------+----------+--------------------+--------------------+--------+----------------+
|  4469|            1|2022-2023|2022-08-27|Brighton & Hove A...|        Leeds United|    true|            0.43|
|  4449|            1|2022-2023|2022-08-13|Brighton & Hove A...|    Newcastle United|   false|           0.411|
|  4460|            1|2022-2023|2022-08-21|        Leeds United|             Chelsea|    true|           0.567|
|  4438|            1|2022-2023|2022-08-06|     AFC Bournemouth|         Aston Villa|   false|           0.402|
|  4437|            1|2022-2023|2022-08-06|              Fulham|           Liverpool|   false|           0.389|
|  4457|            1|2022-2023|2022-08-20|      Crystal Palace|         Aston Villa|   false|           0.592|
|  4457|            1|2022-2023|2022-08-20|      Crystal Palace|         Aston Villa|    true|           0.566|
|  4452|            1|2022-2023|2022-08-13|     Manchester City|     AFC Bournemouth|    true|            0.57|
|  4453|            1|2022-2023|2022-08-14|   Nottingham Forest|            West Ham|    true|           0.427|
|  4462|            1|2022-2023|2022-08-22|   Manchester United|           Liverpool|    true|            0.58|
|  4440|            1|2022-2023|2022-08-07|      Leicester City|           Brentford|    true|             0.6|
|  4448|            1|2022-2023|2022-08-13|           Brentford|   Manchester United|    true|           0.446|
|  4445|            1|2022-2023|2022-08-07|            West Ham|     Manchester City|   false|           0.596|
|  4437|            1|2022-2023|2022-08-06|              Fulham|           Liverpool|    true|           0.427|
|  4474|            1|2022-2023|2022-08-27|         Southampton|   Manchester United|   false|           0.587|
|  4455|            1|2022-2023|2022-08-13|Wolverhampton Wan...|              Fulham|   false|           0.564|
|  4465|            1|2022-2023|2022-08-21|            West Ham|Brighton & Hove A...|   false|           0.571|
|  4451|            1|2022-2023|2022-08-15|           Liverpool|      Crystal Palace|   false|           0.576|
|  4450|            1|2022-2023|2022-08-14|             Chelsea|   Tottenham Hotspur|   false|           0.377|
|  4464|            1|2022-2023|2022-08-20|   Tottenham Hotspur|Wolverhampton Wan...|    true|           0.418|
+------+-------------+---------+----------+--------------------+--------------------+--------+----------------+
only showing top 20 rows

In [29]:
pl_match_stats_22_23 = str(Path().resolve().parent.parent / "data" / "match_stats" / "PL_22_23.csv")

df_pl_match_stats_22_23 = spark.read \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .csv(pl_match_stats_22_23, sep=',')    

df_pl_match_stats_22_23.show()

+---+----------+-------------------+--------------+--------------+----+----+---+----+----+---+------------+---+---+---+---+---+---+---+---+---+---+---+---+-----+-----+-----+----+----+----+----+----+----+----+-----+-----+----+----+----+----+----+----+----+----+----+-----+-----+-----+--------+--------+-----+-----+-------+-------+-------+-------+-----+-------+-------+----+----+------+------+------+------+------+------+------+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+---------+---------+------+------+--------+--------+--------+--------+-----+--------+--------+-----+-----+-------+-------+-------+-------+
|Div|      Date|               Time|      HomeTeam|      AwayTeam|FTHG|FTAG|FTR|HTHG|HTAG|HTR|     Referee| HS| AS|HST|AST| HF| AF| HC| AC| HY| AY| HR| AR|B365H|B365D|B365A| BWH| BWD| BWA| IWH| IWD| IWA| PSH|  PSD|  PSA| WHH| WHD| WHA| VCH| VCD| VCA|MaxH|MaxD|MaxA| AvgH| AvgD| AvgA|B365>2.5|B365<2.5|P>2.5|P<2.5|Max>2.5|Max<2.5|Avg>2.5|Avg<2.5|  AHh|B365AHH|B365AHA|PAHH|PAHA|MaxAHH|MaxAHA|AvgAHH|AvgAHA|B365CH|B365CD|B365CA|BWCH|BWCD|BWCA|IWCH|IWCD|IWCA|PSCH|PSCD|PSCA|WHCH|WHCD|WHCA|VCCH|VCCD|VCCA|MaxCH|MaxCD|MaxCA|AvgCH|AvgCD|AvgCA|B365C>2.5|B365C<2.5|PC>2.5|PC<2.5|MaxC>2.5|MaxC<2.5|AvgC>2.5|AvgC<2.5| AHCh|B365CAHH|B365CAHA|PCAHH|PCAHA|MaxCAHH|MaxCAHA|AvgCAHH|AvgCAHA|
+---+----------+-------------------+--------------+--------------+----+----+---+----+----+---+------------+---+---+---+---+---+---+---+---+---+---+---+---+-----+-----+-----+----+----+----+----+----+----+----+-----+-----+----+----+----+----+----+----+----+----+----+-----+-----+-----+--------+--------+-----+-----+-------+-------+-------+-------+-----+-------+-------+----+----+------+------+------+------+------+------+------+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+---------+---------+------+------+--------+--------+--------+--------+-----+--------+--------+-----+-----+-------+-------+-------+-------+
| E0|05/08/2022|2026-07-07 20:00:00|Crystal Palace|       Arsenal|   0|   2|  A|   0|   1|  A|    A Taylor| 10| 10|  2|  2| 16| 11|  3|  5|  1|  2|  0|  0|  4.2|  3.6| 1.85|4.33| 3.5|1.87| 4.3|3.55|1.85| 4.5| 3.65| 1.89| 4.4| 3.5|1.83| 4.6| 3.5|1.87| 4.6|3.78|1.95| 4.39| 3.59| 1.88|     2.1|    1.72| 2.14| 1.78|   2.19|   1.91|   2.09|   1.76|  0.5|   2.04|   1.89|2.03|1.89|  2.06|  1.91|  2.01|  1.87|   4.5|   3.6|   1.8| 4.5| 3.5|1.83| 4.4|3.55|1.85|4.58|3.63|1.88| 4.8| 3.4|1.78|4.75| 3.5|1.85| 5.01|  3.7| 1.91| 4.56| 3.57| 1.85|      2.1|     1.72|  2.14|  1.78|    2.19|    1.91|    2.08|    1.76|  0.5|    2.09|    1.84| 2.04| 1.88|   2.09|   1.88|   2.03|   1.85|
| E0|06/08/2022|2026-07-07 12:30:00|        Fulham|     Liverpool|   2|   2|  D|   1|   0|  H|    A Madley|  9| 11|  3|  4|  7|  9|  4|  4|  2|  0|  0|  0| 11.0|  6.0| 1.25|10.0|5.75|1.28|12.0|5.75|1.27|11.2| 6.22| 1.28|12.0| 5.5|1.27|13.0| 6.0|1.25|13.0| 6.4|1.31|10.99| 6.05| 1.28|     1.5|    2.62|  1.5|  2.7|   1.54|   2.76|   1.48|   2.63| 1.75|    1.9|   2.03|1.91| 2.0|  1.92|  2.04|  1.89|  1.99|  11.0|  5.75|  1.28|9.25| 6.0|1.29|11.0| 5.5| 1.3|10.5| 6.5|1.29|11.0| 5.5|1.27|11.5| 6.0|1.29|11.95| 6.93|  1.3|10.33|  6.2| 1.28|      1.5|     2.62|  1.49|  2.77|    1.51|     3.0|    1.47|    2.73| 1.75|     1.9|    2.03| 1.91| 2.02|   2.01|   2.06|   1.89|   1.99|
| E0|06/08/2022|2026-07-07 15:00:00|   Bournemouth|   Aston Villa|   2|   0|  H|   1|   0|  H|    P Bankes|  7| 15|  3|  2| 18| 16|  5|  5|  3|  3|  0|  0| 3.75|  3.5|  2.0|3.75| 3.4| 2.0|3.65|3.45|2.05|3.93| 3.58| 2.04|3.75| 3.3|2.05|3.75| 3.3| 2.0| 4.0|3.66| 2.1|  3.8|  3.5| 2.04|     2.0|     1.8|  2.1| 1.81|    2.1|   1.87|   2.03|    1.8|  0.5|   1.87|   2.06|1.88|2.04|  1.88|  2.07|  1.85|  2.04|   4.0|   3.5|  1.95| 3.9| 3.4|1.95|3.85|3.45| 2.0|4.09|3.59| 2.0| 4.0| 3.4|1.95| 4.1| 3.4| 2.0| 4.25| 3.63| 2.06| 3.99| 3.49|  2.0|      2.1|     1.72|  2.13|  1.79|    2.24|    1.81|     2.1|    1.76|  0.5|    1.93|     2.0| 1.93|  2.0|   1.94|   2.04|   1.88|    2.0|
| E0|06/08/2022|2026-07-07 15:00:00|         Leeds|        Wolves|   2|   1|  H|   1|   1|  D|     R Jones| 12| 15|  4|  6| 13|  9|  6|  4|  2|  0|  0|  0| 2.25|  3.4|  3.2| 2.3| 3.3|2.95| 2.3| 3.3|3.15|2.39| 3.33|  3.3|2.25| 3.3| 3.2| 2.3| 3.2| 3.1|2.42|3.54| 3.3| 2.34| 3.34| 3.18|    2.05|    1.85| 2.09| 1.83|   2.11|   1.87|   2.03|   1.81|-0.25|   2.05|   1.88|2.04|1.89|  2.06|   1.9|  2.01|  1.87|  2.37|   3.3|   3.0| 2.4| 3.3|2.75|2.45| 3.3|2.95|2.45|3.44|3.09| 2.4| 3.3| 2.9| 2.4| 3.4| 3.0|  2.5| 3.55| 3.18| 2.43| 3.36| 3.02|     1.95|     1.95|  1.96|  1.94|    2.09|    1.96|    1.96|    1.87|-0.25|    2.08|    1.85|  2.1| 1.84|   2.14|   1.87|   2.08|   1.81|
| E0|06/08/2022|2026-07-07 15:00:00|     Newcastle| Nott'm Forest|   2|   0|  H|   0|   0|  D|    S Hooper| 23|  5| 10|  0|  9| 14| 11|  1|  0|  3|  0|  0| 1.66|  3.8| 5.25|1.65| 3.8| 5.5|1.65| 3.8| 5.5|1.71| 3.74| 5.83|1.67| 3.7|5.25|1.62| 3.7| 5.5|1.72|3.96| 6.0| 1.67|  3.8| 5.57|    2.05|    1.85|  2.1| 1.81|    2.1|   1.86|   2.03|   1.81|-0.75|   1.87|   2.06|1.92|2.01|  1.92|  2.08|  1.86|  2.02|  1.53|   4.0|   6.0|1.58| 3.9| 6.0|1.63| 3.8| 6.0|1.57|4.22| 6.6|1.53| 3.9| 6.5|1.57| 3.9| 7.0| 1.67|  4.3|  7.0| 1.59| 4.07| 6.15|     1.94|     1.96|  1.97|  1.93|    2.06|    1.97|    1.94|    1.89| -1.0|    1.97|    1.96| 1.99| 1.93|   2.19|   1.97|   2.03|   1.86|
| E0|06/08/2022|2026-07-07 15:00:00|     Tottenham|   Southampton|   4|   1|  H|   2|   1|  H|  A Marriner| 18| 10|  8|  2| 11|  6| 10|  2|  3|  0|  0|  0| 1.33|  5.5|  8.5|1.35|5.25|8.25|1.37|5.25|7.75|1.37| 5.39| 9.11|1.35| 5.0| 8.5|1.33| 5.0| 9.0| 1.4| 5.5| 9.2| 1.36| 5.27| 8.64|    1.61|     2.3| 1.65| 2.37|   1.65|   2.48|   1.61|   2.34| -1.5|   2.04|   1.89|2.08|1.85|  2.08|  1.91|  2.03|  1.85|  1.36|   5.0|   8.5|1.36|5.25|8.25|1.37|5.25| 8.0|1.39|5.34|8.55|1.33| 4.8| 9.5|1.33|5.25|10.0|  1.4|  5.5| 10.0| 1.37| 5.24| 8.59|     1.61|      2.3|  1.65|  2.36|    1.67|     2.4|    1.63|    2.31| -1.5|    2.07|    1.86| 2.04| 1.88|   2.08|   1.88|   2.03|   1.85|
| E0|06/08/2022|2026-07-07 17:30:00|       Everton|       Chelsea|   0|   1|  A|   0|   1|  A|    C Pawson|  8| 15|  4|  6| 14| 11|  4| 16|  3|  2|  0|  0|  5.5|  4.0| 1.61| 5.5| 3.8|1.58| 5.5| 3.9|1.63|6.04| 4.06| 1.63| 5.8|3.75|1.62|5.75| 3.7| 1.6| 6.1| 4.2|1.67| 5.74| 3.96| 1.63|    2.02|    1.88| 2.05| 1.86|   2.07|   1.92|   1.99|   1.84| 0.75|   2.11|   1.82|2.13|1.82|  2.13|  1.84|  2.08|   1.8|   6.5|   4.2|  1.55| 6.0| 3.9|1.57|6.25| 3.9| 1.6|6.89|4.16|1.56| 6.5| 3.9|1.53| 6.0| 4.0| 1.6| 7.08|  4.3| 1.64| 6.44| 4.04| 1.57|      2.1|     1.72|  2.13|  1.79|    2.18|    1.86|    2.08|    1.77|  1.0|    1.93|     2.0| 1.94| 1.98|   1.94|   2.11|   1.88|    2.0|
| E0|07/08/2022|2026-07-07 14:00:00|     Leicester|     Brentford|   2|   2|  D|   1|   0|  H|   J Gillett| 14|  8|  5|  3|  6|  5|  5|  6|  0|  0|  0|  0|  2.0| 3.75|  3.5| 2.0| 3.6| 3.6|2.05|3.65|3.55|2.07| 3.69| 3.74| 2.0| 3.6| 3.5|1.95| 3.5| 3.6| 2.1|3.84| 3.8| 2.03| 3.66| 3.64|    1.72|     2.1| 1.79| 2.12|   1.84|   2.17|   1.77|   2.08| -0.5|   2.04|   1.89|2.07|1.87|  2.07|  1.91|  2.02|  1.86|  1.85|   3.8|   4.0|1.88| 3.6| 4.0|1.95|3.65| 3.9|1.96|3.69|4.29|1.88| 3.6| 4.0|1.91| 3.6| 4.2| 2.01| 3.88|  4.4| 1.92| 3.66| 4.08|     1.94|     1.96|   1.9|  2.01|    1.96|    2.07|    1.86|    1.97| -0.5|    1.94|    1.99| 1.96| 1.96|   1.96|   2.04|   1.92|   1.96|
| E0|07/08/2022|2026-07-07 14:00:00|    Man United|      Brighton|   1|   2|  A|   0|   2|  A|   P Tierney| 17| 15|  5|  4|  7| 12|  6|  2|  4|  1|  0|  0|  1.6|  4.2| 5.25|1.62| 3.9| 5.5| 1.6| 4.0|5.75|1.65| 4.14| 5.68| 1.6| 3.9| 5.5|1.57| 3.8|5.75|1.66|4.22|6.12| 1.62| 4.01| 5.68|    1.92|    1.98|  1.9|  2.0|   1.95|    2.0|   1.89|   1.93| -1.0|   2.05|   1.75|2.18|1.77|  2.18|  1.86|  2.09|  1.79|   1.8|  3.75|  4.33|1.75| 3.7| 4.6|1.77| 3.7| 4.6|1.81|3.86|4.72|1.78| 3.6| 4.6| 1.8| 3.7|4.75| 1.83| 3.94|  5.0| 1.78| 3.77| 4.73|     1.89|     2.01|  1.96|  1.94|    1.96|    2.03|     1.9|    1.94|-0.75|    2.06|    1.87| 2.05| 1.88|   2.08|   1.97|    2.0|   1.88|
| E0|07/08/2022|2026-07-07 16:30:00|      West Ham|      Man City|   0|   2|  A|   0|   1|  A|    M Oliver|  6| 14|  1|  2|  8|  4|  1|  4|  0|  1|  0|  0|  8.0|  5.0| 1.36|7.75| 5.0|1.38| 7.5|5.25|1.37|8.58| 5.48| 1.38| 9.0| 5.0|1.33| 8.5| 5.0|1.33| 9.6| 5.6|1.41| 8.32| 5.25| 1.37|    1.53|     2.5| 1.56| 2.59|   1.62|   2.61|   1.54|   2.47|  1.5|   1.86|   2.07|1.88|2.05|   1.9|   2.1|  1.84|  2.04|   7.5|  5.25|  1.36| 7.5| 5.0|1.38| 7.5| 5.0| 1.4| 8.0|5.35|1.41| 8.0| 5.0|1.36| 8.5|5.25|1.36|  8.5| 5.55| 1.42|  7.9| 5.27| 1.39|      1.5|     2.62|  1.52|  2.67|    1.54|    2.82|     1.5|    2.62|  1.5|    1.85|    2.08| 1.85| 2.08|    2.0|   2.12|   1.85|   2.04|
| E0|13/08/2022|2026-07-07 12:30:00|   Aston Villa|       Everton|   2|   1|  H|   1|   0|  H|    M Oliver| 12| 15|  4|  4|  9|  7|  5|  8|  4|  1|  0|  0|  1.8|  3.5| 4.75| 1.8| 3.5|4.75| 1.8|3.55| 4.6|1.83| 3.55| 5.12| 1.8| 3.4|4.75| 1.8| 3.6| 5.0|1.85|3.68|5.12| 1.82| 3.56| 4.87|     2.1|    1.72| 2.15| 1.78|   2.15|   1.82|   2.08|   1.77| -0.5|   1.77|   2.02|1.82| 2.1|  1.83|  2.16|  1.81|  2.07|  1.75|   3.5|   5.0|1.75| 3.6| 4.8|1.75| 3.6| 4.9|1.81|3.64|5.11|1.75| 3.5| 5.0| 1.8| 3.5| 5.0| 1.84| 3.75| 5.37| 1.78| 3.62| 4.95|      2.1|     1.72|  2.23|  1.72|    2.23|    1.81|    2.13|    1.74|-0.75|    2.05|    1.85| 2.07| 1.87|   2.07|    1.9|   2.02|   1.86|
| E0|13/08/2022|2026-07-07 15:00:00|       Arsenal|     Leicester|   4|   2|  H|   2|   0|  H|   D England| 19|  6|  7|  2| 15|  9|  6|  2|  1|  1|  0|  0| 1.53| 4.33| 5.75|1.52| 4.4| 6.0|1.53| 4.4|5.75|1.58| 4.34| 6.22|1.53| 4.2| 5.8| 1.5| 4.2| 6.0| 1.6|4.65|6.42| 1.55| 4.37| 6.04|    1.66|     2.2| 1.71| 2.25|   1.76|    2.3|   1.69|   2.21| -1.0|   1.92|   1.98|1.96|1.96|  1.98|  2.04|  1.91|  1.96|  1.55|  4.33|   5.5|1.57|4.33| 5.5|1.53| 4.2|6.25|1.58|4.42|5.97|1.55| 4.2| 5.8|1.55| 4.4| 6.0|  1.6|  4.7| 6.25| 1.57|  4.4| 5.89|     1.66|      2.2|  1.73|  2.22|    1.76|    2.34|    1.68|    2.22| -1.0|    1.98|    1.92| 1.96| 1.96|   1.99|    2.0|   1.94|   1.94|
| E0|13/08/2022|2026-07-07 15:00:00|      Brighton|     Newcastle|   0|   0|  D|   0|   0|  D|     G Scott| 13|  4|  7|  1|  8|  6|  7|  3|  2|  3|  0|  0| 2.45|  3.2|  3.0|2.35|3.25| 3.1|2.45| 3.2|3.05|2.48| 3.24| 3.22|2.38|3.25| 3.0|2.38|3.13| 3.1|2.54|3.46|3.27| 2.44| 3.25|  3.1|     2.1|    1.72| 2.19| 1.75|   2.21|   1.79|   2.13|   1.73|-0.25|   2.07|   1.83|2.11|1.83|  2.12|  1.89|  2.07|  1.82|  2.37|   3.3|   3.0| 2.4| 3.2| 3.0|2.45|3.25| 3.0| 2.5| 3.3|3.14|2.38| 3.2| 3.1| 2.4|3.25| 3.2| 2.56| 3.38| 3.21| 2.44| 3.28|  3.1|      2.1|     1.72|   2.2|  1.74|     2.2|    1.81|    2.14|    1.73|-0.25|    2.11|    1.79| 2.13| 1.82|   2.14|   1.84|   2.08|   1.81|
| E0|13/08/2022|2026-07-07 15:00:00|      Man City|   Bournemouth|   4|   0|  H|   3|   0|  H|     D Coote| 19|  3|  7|  1|  9|  9| 11|  1|  0|  3|  0|  0| 1.06| 13.0| 29.0|1.07|12.5|41.0|1.08|12.0|27.0|1.07|13.82| 41.0|1.05|13.0|34.0|1.06|11.0|31.0|1.09|16.0|50.0| 1.07|12.72|37.57|    1.33|     3.4| 1.33| 3.45|   1.38|   3.55|   1.33|   3.35|-2.75|   1.88|   2.02|1.87|2.03|   1.9|  2.06|  1.87|  2.01|  1.08|  12.0|  21.0|1.09|11.5|26.0|1.08|12.0|24.0|1.08|13.5|36.0|1.06|11.0|34.0|1.06|13.0|41.0| 1.09| 15.0| 41.0| 1.08|12.66| 32.0|     1.28|     3.75|  1.33|  3.41|    1.34|    3.99|    1.29|    3.67|-2.75|    1.95|    1.95| 1.94| 1.94|   1.98|   2.02|   1.92|   1.95|
| E0|13/08/2022|2026-07-07 15:00:00|   Southampton|         Leeds|   2|   2|  D|   0|   0|  D|T Harrington| 14| 13|  4|  5| 10| 12|  2|  5|  1|  3|  0|  0| 2.25|  3.5|  3.1|2.25| 3.4| 3.1| 2.3|3.45| 3.1|2.34| 3.55| 3.18|2.25| 3.4| 3.1|2.25| 3.4| 3.0| 2.4|3.64| 3.2| 2.32| 3.51|  3.1|    1.72|     2.1| 1.75| 2.19|   1.79|    2.2|   1.73|   2.13|-0.25|   2.01|   1.89|2.02| 1.9|  2.04|  1.91|   2.0|  1.87|   2.4|   3.5|   2.8| 2.4| 3.5| 2.8|2.45| 3.4| 2.9|2.44|3.64|2.96| 2.5| 3.4|2.75| 2.4| 3.6|2.88| 2.57| 3.65|  3.0| 2.44| 3.57| 2.87|     1.61|      2.3|  1.67|  2.33|    1.73|    2.45|    1.65|    2.28|-0.25|    2.09|    1.81| 2.12| 1.83|   2.13|   1.84|    2.1|   1.79|
| E0|13/08/2022|2026-07-07 15:00:00|        Wolves|        Fulham|   0|   0|  D|   0|   0|  D|    J Brooks|  7|  9|  1|  3|  7| 14|  5|  3|  3|  3|  0|  0|  2.3|  3.3|  3.2|2.35|3.25| 3.1| 2.4|3.25| 3.1|2.44| 3.24| 3.29|2.35|3.25| 3.1| 2.3| 3.2| 3.1|2.48|3.46|3.29|  2.4| 3.28| 3.15|     2.1|    1.72| 2.18| 1.75|    2.2|   1.79|   2.11|   1.75|-0.25|   2.04|   1.86|2.07|1.86|  2.07|  1.89|  2.04|  1.84|   2.2|   3.4|   3.3| 2.2| 3.3| 3.3| 2.2| 3.4| 3.3|2.23|3.48| 3.5| 2.2|3.25| 3.4|2.15| 3.4| 3.5| 2.29|  3.5| 3.59| 2.22| 3.41| 3.41|     1.97|     1.93|   2.0|  1.91|    2.02|    2.03|    1.96|    1.88|-0.25|     1.9|     2.0| 1.92| 2.01|   1.95|   2.05|    1.9|   1.98|
| E0|13/08/2022|2026-07-07 17:30:00|     Brentford|    Man United|   4|   0|  H|   4|   0|  H|   S Attwell| 13| 15|  7|  4|  6| 15|  8|  2|  0|  4|  0|  0| 3.75|  3.5|  2.0| 3.7| 3.5| 2.0|3.65|3.55| 2.0|3.82| 3.64| 2.06| 3.8| 3.5|1.95| 3.6| 3.5|1.95|4.04|3.65|2.08| 3.77| 3.56| 2.02|     1.8|     2.0| 1.83| 2.08|   1.86|   2.11|   1.82|   2.02|  0.5|   1.87|   2.03|1.88|2.06|  1.92|  2.08|  1.85|  2.03|   4.5|  3.75|  1.75| 3.6| 3.5| 2.0| 4.3|3.65|1.85|4.65|4.09|1.78|4.75| 3.6|1.75| 4.4| 3.9| 1.8| 5.05| 4.09| 1.97| 4.35| 3.86| 1.83|     1.72|      2.1|  1.74|  2.23|     1.8|    2.36|    1.71|    2.18|  0.5|    2.08|    1.73| 2.17| 1.78|   2.19|   1.95|   2.04|   1.84|
| E0|14/08/2022|2026-07-07 14:00:00| Nott'm Forest|      West Ham|   1|   0|  H|   1|   0|  H|     R Jones| 13| 19|  6|  5| 10| 11|  6|  7|  4|  1|  0|  0|  4.2|  3.6| 1.85| 4.1| 3.6|1.87| 4.1| 3.6| 1.9|4.28| 3.72| 1.92| 4.2| 3.5|1.85| 4.1| 3.5|1.85| 4.4|3.75|1.94| 4.21| 3.64|  1.9|    1.92|    1.98|  1.9| 2.01|   1.95|   2.01|    1.9|   1.93|  0.5|    2.0|    1.9| 2.0|1.92|  2.02|  1.92|  1.98|  1.89|   3.8|   3.5|  1.95| 3.9| 3.6| 1.9|3.95| 3.5|1.95|4.03|3.68|1.99| 4.2| 3.4|1.91| 4.0| 3.6|1.95| 4.48|  3.8| 2.02| 4.01| 3.62| 1.95|     1.91|     1.99|  1.92|  2.01|    1.92|    2.03|    1.88|    1.96|  0.5|     1.9|     2.0| 1.93| 1.99|   1.96|   2.04|   1.92|   1.95|
| E0|14/08/2022|2026-07-07 16:30:00|       Chelsea|     Tottenham|   2|   2|  D|   1|   0|  H|    A Taylor| 16| 10|  3|  5|  9|  9|  8|  5|  3|  0|  0|  0| 2.25|  3.4|  3.2|2.25| 3.4| 3.1| 2.3|3.35|3.15|2.28| 3.52| 3.35|2.25| 3.3| 3.2| 2.2| 3.3| 3.2|2.38|3.55|3.36| 2.29| 3.44| 3.21|    1.98|    1.92| 1.98| 1.92|   2.02|   1.97|   1.94|   1.89|-0.25|   1.95|   1.95|1.96|1.96|  1.99|  1.98|  1.96|  1.92|   2.1|   3.5|   3.5|2.15| 3.4| 3.3|2.15|3.35|3.45|2.17|3.53|3.61| 2.2| 3.3| 3.3|2.15| 3.5| 3.5| 2.25|  3.6| 3.65| 2.16| 3.49| 3.48|     1.95|     1.95|  1.95|  1.95|    1.99|    2.03|    1.92|    1.93|-0.25|    1.86|    2.04| 1.87| 2.07|   1.92|   2.07|   1.86|   2.02|
| E0|15/08/2022|2026-07-07 20:00:00|     Liverpool|Crystal Palace|   1|   1|  D|   0|   1|  A|   P Tierney| 24|  7|  4|  3|  7|  8|  4|  2|  2|  4|  1|  0| 1.18| 6.75| 16.0| 1.2|6.75|15.0| 1.2|6.75|15.0| 1.2| 7.09|18.57|1.18| 6.5|17.0|1.15| 7.0|17.0|1.23|7.23|19.0|  1.2| 6.85|16.33|    1.57|    2.37| 1.57| 2.52|   1.57|   2.57|   1.55|   2.46| -2.0|   2.01|   1.89|2.04|1.87|  2.06|  1.93|   2.0|  1.86|  1.28|  5.75|  11.0|1.28|5.75|10.5| 1.3|5.75|11.0|1.29|6.25|12.0|1.27| 5.5|12.0|1.25| 6.0|13.0|  1.3|  7.0| 14.5| 1.27|  6.1|11.72|     1.57|     2.37|  1.61|  2.42|    1.63|    2.47|    1.59|     2.4|-1.75|    2.06|    1.84| 2.08| 1.83|   2.08|   2.09|   2.02|   1.86|
+---+----------+-------------------+--------------+--------------+----+----+---+----+----+---+------------+---+---+---+---+---+---+---+---+---+---+---+---+-----+-----+-----+----+----+----+----+----+----+----+-----+-----+----+----+----+----+----+----+----+----+----+-----+-----+-----+--------+--------+-----+-----+-------+-------+-------+-------+-----+-------+-------+----+----+------+------+------+------+------+------+------+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+---------+---------+------+------+--------+--------+--------+--------+-----+--------+--------+-----+-----+-------+-------+-------+-------+
only showing top 20 rows

In [34]:
df_pl_match_stats_22_23_filtrado = df_pl_match_stats_22_23.select(
    F.to_date(F.col("Date"), "dd/MM/yyyy").alias("date"),
    F.col('HomeTeam').alias('homeTeamName'),
    F.col('AwayTeam').alias('opponentTeamName'),
    'FTHG',
    'FTAG',
    'FTR',
    #'HTHG',
    #'HTAG',
    #'HTR',
    'HS',
    'AS',
    'HST',
    'AST',    
    'AvgH',
    'AvgA',
    'AvgD'
).sort('date')

In [48]:
team_name_mapping = {
    "Tottenham": "Tottenham Hotspur",
    "Brighton": "Brighton & Hove Albion",
    "Man City": "Manchester City",
    "Crystal Palace": "Crystal Palace",
    "Leicester": "Leicester City",
    "Aston Villa": "Aston Villa",
    "Bournemouth": "AFC Bournemouth",
    "Fulham": "Fulham",
    "West Ham": "West Ham",
    "Man United": "Manchester United",
    "Wolves": "Wolverhampton Wanderers",
    "Southampton": "Southampton",
    "Liverpool": "Liverpool",
    "Chelsea": "Chelsea",
    "Nott'm Forest": "Nottingham Forest",
    "Newcastle": "Newcastle United",
    "Everton": "Everton",
    "Leeds": "Leeds United",
    "Arsenal": "Arsenal",
    "Brentford": "Brentford"
}

df_pl_match_stats_22_23_filtrado_mapped = (
    df_pl_match_stats_22_23_filtrado
    .replace(team_name_mapping, subset=["homeTeamName", "opponentTeamName"])
)

df_pl_match_stats_22_23_filtrado_mapped.show()

+----------+--------------------+--------------------+----+----+---+---+---+---+---+-----+-----+-----+
|      date|        homeTeamName|    opponentTeamName|FTHG|FTAG|FTR| HS| AS|HST|AST| AvgH| AvgA| AvgD|
+----------+--------------------+--------------------+----+----+---+---+---+---+---+-----+-----+-----+
|2022-08-05|      Crystal Palace|             Arsenal|   0|   2|  A| 10| 10|  2|  2| 4.39| 1.88| 3.59|
|2022-08-06|              Fulham|           Liverpool|   2|   2|  D|  9| 11|  3|  4|10.99| 1.28| 6.05|
|2022-08-06|     AFC Bournemouth|         Aston Villa|   2|   0|  H|  7| 15|  3|  2|  3.8| 2.04|  3.5|
|2022-08-06|        Leeds United|Wolverhampton Wan...|   2|   1|  H| 12| 15|  4|  6| 2.34| 3.18| 3.34|
|2022-08-06|    Newcastle United|   Nottingham Forest|   2|   0|  H| 23|  5| 10|  0| 1.67| 5.57|  3.8|
|2022-08-06|   Tottenham Hotspur|         Southampton|   4|   1|  H| 18| 10|  8|  2| 1.36| 8.64| 5.27|
|2022-08-06|             Everton|             Chelsea|   0|   1|  A|  8| 15|  4|  6| 5.74| 1.63| 3.96|
|2022-08-07|      Leicester City|           Brentford|   2|   2|  D| 14|  8|  5|  3| 2.03| 3.64| 3.66|
|2022-08-07|   Manchester United|Brighton & Hove A...|   1|   2|  A| 17| 15|  5|  4| 1.62| 5.68| 4.01|
|2022-08-07|            West Ham|     Manchester City|   0|   2|  A|  6| 14|  1|  2| 8.32| 1.37| 5.25|
|2022-08-13|         Aston Villa|             Everton|   2|   1|  H| 12| 15|  4|  4| 1.82| 4.87| 3.56|
|2022-08-13|             Arsenal|      Leicester City|   4|   2|  H| 19|  6|  7|  2| 1.55| 6.04| 4.37|
|2022-08-13|Brighton & Hove A...|    Newcastle United|   0|   0|  D| 13|  4|  7|  1| 2.44|  3.1| 3.25|
|2022-08-13|     Manchester City|     AFC Bournemouth|   4|   0|  H| 19|  3|  7|  1| 1.07|37.57|12.72|
|2022-08-13|         Southampton|        Leeds United|   2|   2|  D| 14| 13|  4|  5| 2.32|  3.1| 3.51|
|2022-08-13|Wolverhampton Wan...|              Fulham|   0|   0|  D|  7|  9|  1|  3|  2.4| 3.15| 3.28|
|2022-08-13|           Brentford|   Manchester United|   4|   0|  H| 13| 15|  7|  4| 3.77| 2.02| 3.56|
|2022-08-14|   Nottingham Forest|            West Ham|   1|   0|  H| 13| 19|  6|  5| 4.21|  1.9| 3.64|
|2022-08-14|             Chelsea|   Tottenham Hotspur|   2|   2|  D| 16| 10|  3|  5| 2.29| 3.21| 3.44|
|2022-08-15|           Liverpool|      Crystal Palace|   1|   1|  D| 24|  7|  4|  3|  1.2|16.33| 6.85|
+----------+--------------------+--------------------+----+----+---+---+---+---+---+-----+-----+-----+
only showing top 20 rows

In [67]:
df_avg_threat_match_stats = (
    df_avg_threat.join(
        df_pl_match_stats_22_23_filtrado_mapped,
        on= ['date', 'homeTeamName', 'opponentTeamName'],
        how='left'
    )
)

df_avg_threat_match_stats.show()

+----------+--------------------+--------------------+------+-------------+---------+--------+----------------+----+----+---+---+---+---+---+-----+-----+-----+
|      date|        homeTeamName|    opponentTeamName|gameId|competitionId|   season|homeTeam|avg_threat_score|FTHG|FTAG|FTR| HS| AS|HST|AST| AvgH| AvgA| AvgD|
+----------+--------------------+--------------------+------+-------------+---------+--------+----------------+----+----+---+---+---+---+---+-----+-----+-----+
|2022-08-27|Brighton & Hove A...|        Leeds United|  4469|            1|2022-2023|    true|            0.43|   1|   0|  H| 13| 10|  4|  2| 1.91| 4.04| 3.73|
|2022-08-13|Brighton & Hove A...|    Newcastle United|  4449|            1|2022-2023|   false|           0.411|   0|   0|  D| 13|  4|  7|  1| 2.44|  3.1| 3.25|
|2022-08-21|        Leeds United|             Chelsea|  4460|            1|2022-2023|    true|           0.567|   3|   0|  H| 12| 14|  6|  3| 5.93| 1.55| 4.43|
|2022-08-06|     AFC Bournemouth|         Aston Villa|  4438|            1|2022-2023|   false|           0.402|   2|   0|  H|  7| 15|  3|  2|  3.8| 2.04|  3.5|
|2022-08-06|              Fulham|           Liverpool|  4437|            1|2022-2023|   false|           0.389|   2|   2|  D|  9| 11|  3|  4|10.99| 1.28| 6.05|
|2022-08-20|      Crystal Palace|         Aston Villa|  4457|            1|2022-2023|   false|           0.592|   3|   1|  H| 17| 13|  9|  5| 2.52|  3.0|  3.2|
|2022-08-20|      Crystal Palace|         Aston Villa|  4457|            1|2022-2023|    true|           0.566|   3|   1|  H| 17| 13|  9|  5| 2.52|  3.0|  3.2|
|2022-08-13|     Manchester City|     AFC Bournemouth|  4452|            1|2022-2023|    true|            0.57|   4|   0|  H| 19|  3|  7|  1| 1.07|37.57|12.72|
|2022-08-14|   Nottingham Forest|            West Ham|  4453|            1|2022-2023|    true|           0.427|   1|   0|  H| 13| 19|  6|  5| 4.21|  1.9| 3.64|
|2022-08-22|   Manchester United|           Liverpool|  4462|            1|2022-2023|    true|            0.58|   2|   1|  H| 12| 17|  4|  5| 5.22|  1.6| 4.38|
|2022-08-07|      Leicester City|           Brentford|  4440|            1|2022-2023|    true|             0.6|   2|   2|  D| 14|  8|  5|  3| 2.03| 3.64| 3.66|
|2022-08-13|           Brentford|   Manchester United|  4448|            1|2022-2023|    true|           0.446|   4|   0|  H| 13| 15|  7|  4| 3.77| 2.02| 3.56|
|2022-08-07|            West Ham|     Manchester City|  4445|            1|2022-2023|   false|           0.596|   0|   2|  A|  6| 14|  1|  2| 8.32| 1.37| 5.25|
|2022-08-06|              Fulham|           Liverpool|  4437|            1|2022-2023|    true|           0.427|   2|   2|  D|  9| 11|  3|  4|10.99| 1.28| 6.05|
|2022-08-27|         Southampton|   Manchester United|  4474|            1|2022-2023|   false|           0.587|   0|   1|  A| 17| 11|  5|  6| 4.27|  1.8| 4.06|
|2022-08-13|Wolverhampton Wan...|              Fulham|  4455|            1|2022-2023|   false|           0.564|   0|   0|  D|  7|  9|  1|  3|  2.4| 3.15| 3.28|
|2022-08-21|            West Ham|Brighton & Hove A...|  4465|            1|2022-2023|   false|           0.571|   0|   2|  A| 13| 11|  3|  2| 2.32| 3.14| 3.41|
|2022-08-15|           Liverpool|      Crystal Palace|  4451|            1|2022-2023|   false|           0.576|   1|   1|  D| 24|  7|  4|  3|  1.2|16.33| 6.85|
|2022-08-14|             Chelsea|   Tottenham Hotspur|  4450|            1|2022-2023|   false|           0.377|   2|   2|  D| 16| 10|  3|  5| 2.29| 3.21| 3.44|
|2022-08-20|   Tottenham Hotspur|Wolverhampton Wan...|  4464|            1|2022-2023|    true|           0.418|   1|   0|  H| 11| 20|  4|  3| 1.41| 7.96| 4.88|
+----------+--------------------+--------------------+------+-------------+---------+--------+----------------+----+----+---+---+---+---+---+-----+-----+-----+
only showing top 20 rows

In [71]:
df_pl_match_stats_22_23_filtrado_mapped_home = df_avg_threat_match_stats.filter(
    F.col('homeTeam')
    ).select(
    "date",
    F.col("homeTeamName").alias("teamName"),
    "avg_threat_score",
    (F.col("FTR") == 'H').alias('win'),
    F.col("FTHG").alias("goals"),
    F.col("HS").alias("shots"),
    F.col("HST").alias("shots_target"),
    F.col("AvgH").alias("avg_win_odds")
)

df_pl_match_stats_22_23_filtrado_mapped_away = df_avg_threat_match_stats.filter(
    ~F.col('homeTeam')
    ).select(
    "date",
    F.col("opponentTeamName").alias("teamName"),
    "avg_threat_score",
    (F.col("FTR") == 'A').alias('win'),
    F.col("FTAG").alias("goals"),
    F.col("AS").alias("shots"),
    F.col("AST").alias("shots_target"),
    F.col("AvgA").alias("avg_win_odds")
)

df_team_match = df_pl_match_stats_22_23_filtrado_mapped_home.unionByName(df_pl_match_stats_22_23_filtrado_mapped_away)
df_team_match.show()

+----------+--------------------+----------------+-----+-----+-----+------------+------------+
|      date|            teamName|avg_threat_score|  win|goals|shots|shots_target|avg_win_odds|
+----------+--------------------+----------------+-----+-----+-----+------------+------------+
|2022-08-27|Brighton & Hove A...|            0.43| true|    1|   13|           4|        1.91|
|2022-08-21|        Leeds United|           0.567| true|    3|   12|           6|        5.93|
|2022-08-20|      Crystal Palace|           0.566| true|    3|   17|           9|        2.52|
|2022-08-13|     Manchester City|            0.57| true|    4|   19|           7|        1.07|
|2022-08-14|   Nottingham Forest|           0.427| true|    1|   13|           6|        4.21|
|2022-08-22|   Manchester United|            0.58| true|    2|   12|           4|        5.22|
|2022-08-07|      Leicester City|             0.6|false|    2|   14|           5|        2.03|
|2022-08-13|           Brentford|           0.446| true|    4|   13|           7|        3.77|
|2022-08-06|              Fulham|           0.427|false|    2|    9|           3|       10.99|
|2022-08-20|   Tottenham Hotspur|           0.418| true|    1|   11|           4|        1.41|
|2022-08-13|         Aston Villa|           0.415| true|    2|   12|           4|        1.82|
|2022-08-07|            West Ham|           0.608|false|    0|    6|           1|        8.32|
|2022-08-15|           Liverpool|           0.578|false|    1|   24|           4|         1.2|
|2022-08-13|Wolverhampton Wan...|           0.599|false|    0|    7|           1|         2.4|
|2022-08-20|      Leicester City|           0.396|false|    1|    6|           1|        1.85|
|2022-08-21|    Newcastle United|           0.566|false|    3|   12|           6|        8.67|
|2022-08-27|           Brentford|           0.413|false|    1|   19|           5|        2.06|
|2022-08-06|     AFC Bournemouth|           0.403| true|    2|    7|           3|         3.8|
|2022-08-07|   Manchester United|           0.583|false|    1|   17|           5|        1.62|
|2022-08-14|             Chelsea|           0.433|false|    2|   16|           3|        2.29|
+----------+--------------------+----------------+-----+-----+-----+------------+------------+
only showing top 20 rows

In [90]:
df_team_match_pd = df_team_match.toPandas()
df_team_match_pd.drop(['date', 'teamName'], axis=1).corr()

,avg_threat_score,win,goals,shots,shots_target,avg_win_odds
avg_threat_score,1.000000,0.001259,-0.023419,-0.011282,-0.022424,0.017894
win,0.001259,1.000000,0.620001,0.252019,0.385947,-0.287305
goals,-0.023419,0.620001,1.000000,0.330004,0.587279,-0.224993
shots,-0.011282,0.252019,0.330004,1.000000,0.695799,-0.421675
shots_target,-0.022424,0.385947,0.587279,0.695799,1.000000,-0.306992
avg_win_odds,0.017894,-0.287305,-0.224993,-0.421675,-0.306992,1.000000

In [ ]:
# Saldo do time da casa na temporada
df_avg_threat_teams_season = (
    df_team_match.groupby(
        'TeamName'
        )
    .agg(
        F.median(F.col('avg_threat_score')).alias('avg_threat_score'),
        
        F.round(F.mean(F.when(F.col("win"), 1).otherwise(0)), 2).alias("win_score"),
        
        F.sum(F.col('goals')).alias('total_goals'),
        F.round(F.mean(F.col('goals')), 2).alias('avg_goals'),
        
        F.sum(F.col('shots')).alias('total_shots'),
        F.round(F.mean(F.col('shots')), 2).alias('avg_shots'),
        
        F.sum(F.col('shots_target')).alias('total_shots_target'),
        F.round(F.mean(F.col('shots_target')), 2).alias('avg_shots_target'),
        
        F.round(F.median(F.col('avg_win_odds')), 2).alias('avg_win_odds'),       
    ).sort('win_score', ascending=False)
)

#df_avg_threat_teams_season.show()

+--------------------+----------------+---------+-----------+---------+-----------+---------+------------------+----------------+------------+
|            TeamName|avg_threat_score|win_score|total_goals|avg_goals|total_shots|avg_shots|total_shots_target|avg_shots_target|avg_win_odds|
+--------------------+----------------+---------+-----------+---------+-----------+---------+------------------+----------------+------------+
|     Manchester City|            0.56|     0.73|         91|     2.46|        594|    16.05|               215|            5.81|         1.3|
|             Arsenal|           0.438|      0.7|         88|     2.38|        578|    15.62|               201|            5.43|        1.59|
|   Manchester United|           0.556|     0.59|         56|     1.51|        580|    15.68|               210|            5.68|        1.89|
|           Liverpool|           0.553|     0.51|         75|     2.03|        582|    15.73|               204|            5.51|        1.54|
|    Newcastle United|            0.53|     0.49|         64|     1.73|        556|    15.03|               189|            5.11|        2.05|
|   Tottenham Hotspur|           0.564|     0.49|         69|     1.86|        512|    13.84|               198|            5.35|        2.13|
|         Aston Villa|           0.422|     0.46|         49|     1.32|        422|    11.41|               146|            3.95|        2.79|
|Brighton & Hove A...|           0.447|     0.46|         68|     1.84|        593|    16.03|               223|            6.03|        2.15|
|           Brentford|           0.446|     0.41|         58|     1.57|        385|    10.41|               158|            4.27|        3.49|
|              Fulham|           0.545|     0.38|         52|     1.41|        408|    11.03|               142|            3.84|        3.25|
|      Crystal Palace|           0.434|      0.3|         40|     1.08|        416|    11.24|               134|            3.62|        3.59|
|     AFC Bournemouth|           0.447|      0.3|         37|      1.0|        348|     9.41|               131|            3.54|        4.99|
|            West Ham|           0.536|      0.3|         42|     1.14|        460|    12.43|               141|            3.81|        2.81|
|Wolverhampton Wan...|           0.563|     0.27|         29|     0.78|        406|    10.97|               121|            3.27|        3.31|
|             Chelsea|           0.433|     0.27|         37|      1.0|        469|    12.68|               152|            4.11|        1.95|
|   Nottingham Forest|           0.564|     0.24|         37|      1.0|        354|     9.57|               113|            3.05|        5.05|
|      Leicester City|           0.568|     0.22|         49|     1.32|        395|    10.68|               144|            3.89|        3.24|
|        Leeds United|           0.546|     0.19|         48|      1.3|        457|    12.35|               145|            3.92|        3.33|
|         Southampton|           0.546|     0.14|         34|     0.92|        404|    10.92|               137|             3.7|        4.01|
|             Everton|           0.548|     0.11|         18|     0.95|        197|    10.37|                63|            3.32|        4.76|
+--------------------+----------------+---------+-----------+---------+-----------+---------+------------------+----------------+------------+

In [87]:
df_avg_threat_teams_season_pd = df_avg_threat_teams_season.toPandas()
df_avg_threat_teams_season_pd.drop('TeamName', axis=1).corr('spearman')

,avg_threat_score,win_score,total_goals,avg_goals,total_shots,avg_shots,total_shots_target,avg_shots_target,avg_win_odds
avg_threat_score,1.000000,-0.129811,0.000000,-0.003771,-0.066993,-0.065487,-0.091080,-0.105382,0.026346
win_score,-0.129811,1.000000,0.870469,0.860650,0.762913,0.744820,0.805883,0.791559,-0.782513
total_goals,0.000000,0.870469,1.000000,0.995472,0.755557,0.743504,0.885877,0.878344,-0.762337
avg_goals,-0.003771,0.860650,0.995472,1.000000,0.738984,0.732958,0.875331,0.875331,-0.753297
total_shots,-0.066993,0.762913,0.755557,0.738984,1.000000,0.995489,0.873684,0.861654,-0.902256
avg_shots,-0.065487,0.744820,0.743504,0.732958,0.995489,1.000000,0.867669,0.863158,-0.906767
total_shots_target,-0.091080,0.805883,0.885877,0.875331,0.873684,0.867669,1.000000,0.995489,-0.855639
avg_shots_target,-0.105382,0.791559,0.878344,0.875331,0.861654,0.863158,0.995489,1.000000,-0.851128
avg_win_odds,0.026346,-0.782513,-0.762337,-0.753297,-0.902256,-0.906767,-0.855639,-0.851128,1.000000